### ISSUE TITLE
Add dep consumer test

### ISSUE THREAD

**Issue by carolynvs** [cnabio/duffle#759]
Add a test that ensures that a consumer of duffle can get us to work with just a single constraint in the Gopkg.toml and not need any additional constraints or overrides.

**Comment by glyn** [comment]
Alternatively: https://github.com/deislabs/duffle/issues/760

**Comment by carolynvs** [comment]
Yeah if the project wants to make the decision to use go modules (and force all downstream consumers to do so as well), that's an alternative. Not one I'm eager to switch to for obvious reasons, but I'll stay out of it.

**Comment by radu-matei** [comment]
closed by #887
