### ISSUE TITLE
Switch from dep to go modules

### ISSUE THREAD

**Issue by glyn** [cnabio/duffle#760]
Later this year, GOPATH will be deprecated and Go 1.13 will make modules mode the default. So we should consider moving to go modules for duffle. At the same time, we should delete the `vendor/` directory.

For comparison, we did this on several repositories related to the riff open source project and the advantages generally outweighed any small issues that cropped up (typically "point in time" issues due to mocking libraries needing to support Go modules, which most now do).

**Comment by radu-matei** [comment]
closed by #887
