### ISSUE TITLE
building master fails for me, pointers?

### ISSUE THREAD

**Issue by tomsherrod** [cnabio/duffle#892]
Initial "make build" fails:
docker run -it --rm -e SKIP_DOCKER=true -v /home/centos/gowork/src/github.com/cnabio/duffle/:/go/src/github.com/cnabio/duffle -w /go/src/github.com/cnabio/duffl
e quay.io/deis/lightweight-docker-go:v0.7.0 bash -c "LDFLAGS=\"-w -s -X github.com/cnabio/duffle/pkg/version.Version=ff921e4-dirty\" scripts/build.sh"
building linux-amd64
cmd/duffle/bundle_remove.go:12:2: cannot find package "github.com/Masterminds/semver" in any of:
        /usr/local/go/src/github.com/Masterminds/semver (from $GOROOT)
        /go/src/github.com/Masterminds/semver (from $GOPATH)
cmd/duffle/install.go:15:2: cannot find package "github.com/cnabio/cnab-go/action" in any of:
        /usr/local/go/src/github.com/cnabio/cnab-go/action (from $GOROOT)
        /go/src/github.com/cnabio/cnab-go/action (from $GOPATH)
cmd/duffle/build.go:11:2: cannot find package "github.com/cnabio/cnab-go/bundle" in any of:
        /usr/local/go/src/github.com/cnabio/cnab-go/bundle (from $GOROOT)
        /go/src/github.com/cnabio/cnab-go/bundle (from $GOPATH)
cmd/duffle/install.go:17:2: cannot find package "github.com/cnabio/cnab-go/bundle/definition" in any of:
        /usr/local/go/src/github.com/cnabio/cnab-go/bundle/definition (from $GOROOT)
        /go/src/github.com/cnabio/cnab-go/bundle/definition (from $GOPATH)

Modify Makefile to set /go to GOPATH:
 make build
docker run -it --rm -e SKIP_DOCKER=true -v /home/centos/gowork:/go -w /go/src/github.com/cnabio/duffle quay.io/deis/lightweight-docker-go:v0.7.0 bash -c "LDFLAGS=\"-w -s -X github.com/cnabio/duffle/pkg/version.Version=ff921e4-dirty\" scripts/build.sh"
building linux-amd64
# github.com/docker/cli/cli/config
../../docker/cli/cli/config/config.go:109:18: undefined: os.UserHomeDir
# k8s.io/apimachinery/pkg/util/errors
/go/src/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
# sigs.k8s.io/structured-merge-diff/value
/go/src/sigs.k8s.io/structured-merge-diff/value/mapreflect.go:95:13: val.MapRange undefined (type reflect.Value has no field or method MapRange)
/go/src/sigs.k8s.io/structured-merge-diff/value/mapreflect.go:173:14: rhs.MapRange undefined (type reflect.Value has no field or method MapRange)
/go/src/sigs.k8s.io/structured-merge-diff/value/mapreflect.go:194:13: lhs.MapRange undefined (type reflect.Value has no field or method MapRange)
# k8s.io/client-go/transport
/go/src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
/go/src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
/go/src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
/go/src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
# github.com/cnabio/duffle/pkg/builder
pkg/builder/builder.go:83:3: cannot use ctx.Manifest.SchemaVersion (type string) as type schemaversion.SchemaVersion in field value
# github.com/pivotal/image-relocation/pkg/image
../../pivotal/image-relocation/pkg/image/name.go:128:55: cannot use digest.dig (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest
# github.com/google/go-containerregistry/pkg/logs
../../google/go-containerregistry/pkg/logs/logs.go:38:10: l.Writer undefined (type *log.Logger has no field or method Writer)
# github.com/google/go-containerregistry/vendor/github.com/docker/cli/cli/config
../../google/go-containerregistry/vendor/github.com/docker/cli/cli/config/config.go:109:18: undefined: os.UserHomeDir
make: *** [build-all-bins] Error 2

Pointers? What am I missing?
Thanks,
Tom

**Comment by vdice** [comment]
Thank you for this issue @tomsherrod .  I was able to reproduce the same behavior.

I've put up a PR to fix the build.  I added a few other changes in CI to support continually testing this Docker-based build in the future.  The main cause of the build failure was the use of an outdated build image (hadn't been rev'd to support Go modules, apparently)... a good excuse to get us on an official golang image (`golang:1.13`)
